import Head from "next/head";

export default function Cabecalho(){
    return(
        <Head>
            <title>Cajugram Mármores e Granitos</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <meta name="author" content="Marcos Henrique Marcarini Junior" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
    )
}